dist: xenial

language: node_js
node_js: '12'

script:
  # - yarn test
  - yarn build

before_deploy: scripts/before-deploy.sh

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: dist
    on:
      branch: develop
